import { motion } from "framer-motion";

const kernelTypes = [
  { name: "Monolithic Kernel", desc: "All OS services run in kernel space. Fast but less modular.", layers: ["User Apps", "System Call Interface", "File System | Process Mgmt | Memory Mgmt | Device Drivers", "Hardware"] },
  { name: "Microkernel", desc: "Minimal kernel with services running in user space. More modular and reliable.", layers: ["User Apps | File Server | Device Driver", "IPC (Message Passing)", "Microkernel (Scheduling, IPC, Memory)", "Hardware"] },
  { name: "Layered Architecture", desc: "OS divided into layers, each built on top of the one below.", layers: ["Layer N: User Interface", "Layer N-1: User Programs", "Layer 2: Memory Management", "Layer 1: CPU Scheduling", "Layer 0: Hardware"] },
  { name: "Modular Kernel", desc: "Core kernel with loadable modules. Combines benefits of monolithic and micro.", layers: ["Loadable Modules (FS, Net, Drivers)", "Core Kernel", "Hardware"] },
];

const bootSteps = [
  { step: "1", label: "Power ON", desc: "Electrical power reaches the motherboard" },
  { step: "2", label: "BIOS/UEFI", desc: "Firmware performs POST (Power-On Self Test)" },
  { step: "3", label: "Bootloader", desc: "GRUB/Windows Boot Manager loads the kernel" },
  { step: "4", label: "Kernel Loads", desc: "OS kernel initializes drivers and memory" },
  { step: "5", label: "OS Starts", desc: "Init system starts services and user interface" },
];

const interruptTypes = [
  { name: "Hardware Interrupt", desc: "Generated by hardware devices (keyboard, mouse, disk). Signals CPU that a device needs attention." },
  { name: "Software Interrupt", desc: "Generated by programs using system calls (trap). Used to request OS services." },
  { name: "Interrupt Handling", desc: "CPU saves current state → jumps to ISR (Interrupt Service Routine) → processes interrupt → restores state → resumes execution." },
];

export default function OSStructure() {
  return (
    <div className="p-6 md:p-10 max-w-5xl mx-auto space-y-10">
      <h1 className="text-3xl font-bold text-gradient">Computer System Structure & OS Architecture</h1>

      {/* System Architecture Diagram */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Computer System Architecture</h2>
        <div className="flex flex-col items-center gap-2">
          {["CPU (Processor)", "System Bus", "Memory (RAM)", "I/O Devices"].map((item, i) => (
            <motion.div key={item} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.1 }}
              className="diagram-node w-64 text-center">{item}</motion.div>
          ))}
        </div>
        <p className="text-sm text-muted-foreground text-center">The System Bus connects the CPU, Memory, and I/O devices for data transfer.</p>
      </section>

      {/* Kernel Types */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Kernel & OS Structure Types</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {kernelTypes.map((k) => (
            <div key={k.name} className="rounded-lg border border-border bg-card p-4 space-y-3">
              <h3 className="font-semibold text-primary text-sm">{k.name}</h3>
              <p className="text-xs text-muted-foreground">{k.desc}</p>
              <div className="space-y-1">
                {k.layers.map((l, i) => (
                  <div key={i} className="text-xs rounded bg-secondary px-3 py-1.5 text-secondary-foreground text-center font-mono">{l}</div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Booting Process */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Booting Process</h2>
        <div className="flex flex-col gap-3">
          {bootSteps.map((s, i) => (
            <motion.div key={s.step} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.15 }}
              className="flex items-start gap-4 rounded-lg border border-border bg-card p-4">
              <div className="h-8 w-8 rounded-full bg-gradient-primary flex items-center justify-center text-primary-foreground font-bold text-sm shrink-0">{s.step}</div>
              <div>
                <h3 className="font-medium text-card-foreground text-sm">{s.label}</h3>
                <p className="text-xs text-muted-foreground">{s.desc}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Interrupts */}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">Interrupts</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {interruptTypes.map((t) => (
            <div key={t.name} className="rounded-lg border border-border bg-card p-4 space-y-2">
              <h3 className="font-semibold text-primary text-sm">{t.name}</h3>
              <p className="text-xs text-muted-foreground">{t.desc}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
